AllCops:
  Include:
    - ./**/*.rb
  Exclude:
    - moduleroot/spec/spec_helper.rb
    - moduleroot/spec/classes/coverage_spec.rb
    - vendor/**/*
    - modules/**/*

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120

# dealbreaker:
Style/TrailingCommaInArguments:
  Enabled: false

# Disable warnings on moduleroot/spec/spec_helper.rb and other files
Security/YAMLLoad:
  Enabled: false
