---
notifications:
  email: false
sudo: false
language: ruby
cache: bundler
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rubocop'
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
  - rvm: 2.2.5
  - rvm: 2.3.3
branches:
  only:
  - master
