---
.travis.yml:
  rvm:
  - 2.2
  - 2.3
  - 2.4
  env:
  - CHECK=rubocop
  - PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_VERSION="~> 4.8.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_VERSION="~> 5.0.0" STRICT_VARIABLES=yes CHECK=test
  excludes:
  - rvm: 2.2
    env: CHECK=rubocop
  extras:
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=build DEPLOY_TO_FORGE=yes
  docker_sets:
  docker_defaults:
    # values will replace @@SET@@ with the docker_sets' value
    rvm: 2.3
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_TESTMODE=@@TESTMODE@@ BEAKER_set=@@SET@@ CHECK=beaker
    bundler_args: --without development
Gemfile:
  required:
    ':test':
      - gem: puppetlabs_spec_helper
        version: '~> 2.1.1'
      - gem: rspec-puppet
        version: '~> 2.5'
      - gem: rspec-puppet-facts
      - gem: rspec-puppet-utils
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: semantic_puppet
      - gem: metadata-json-lint
      - gem: puppet-blacksmith
      - gem: pry
      - gem: voxpupuli-release
        git: https://github.com/voxpupuli/voxpupuli-release-gem
      - gem: puppet-strings
        version: '~> 1.0'
      - gem: redcarpet
      - gem: gettext-setup
      - gem: xmlrpc
        ruby-operator: '>='
        ruby-version: '2.4.0'
      - gem: rubocop
        version: '~> 0.48.0'
        ruby-operator: '>='
        ruby-version: '2.3.0'
      - gem: rubocop-rspec
        version: '~> 1.15.0'
        ruby-operator: '>='
        ruby-version: '2.3.0'
      - gem: mocha
        version: '>= 1.2.1'
      - gem: coveralls
      - gem: simplecov-console
      - gem: github_changelog_generator
        version: '~> 1.13.0'
        ruby-operator: '<'
        ruby-version: '2.2.2'
      - gem: listen
        version: '<= 3.0.6'
        ruby-operator: '<'
        ruby-version: '2.2.5'
      - gem: rack
        version: '~> 1.0'
        ruby-operator: '<'
        ruby-version: '2.2.2'
      - gem: github_changelog_generator
        ruby-operator: '>='
        ruby-version: '2.2.2'
      - gem: parallel_tests
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
      - gem: overcommit
        version: '~> 0.39.1'
    ':system_tests':
      - gem: beaker
        version: '<= 2.51.0'
        ruby-operator: '<'
        ruby-version: '2.2.5'
      - gem: progressbar
      - gem: beaker-rspec
      - gem: serverspec
      - gem: beaker-puppet_install_helper
        require: false
      - gem: beaker-testmode_switcher
      - gem: beaker-pe
      - gem: beaker-answers
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_140chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  default_enabled_rake_targets:
  - 'metadata_lint'
  - 'release_checks'
...
# vim: syntax=yaml
